"""Child agent factory for creating agents from ChildSpawned events.

Handles child agent creation with hierarchy limits propagation.
"""

import logging
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any
from uuid import UUID

from core.domain.values.context import SpawnPayload
from core.domain.events.events import ChildSpawned
from core.domain.aggregates.agent_session import AgentRole, AgentSession

logger = logging.getLogger(__name__)


if TYPE_CHECKING:
    from config import ManagerConfig
    from core.application.services.agent_repository import AgentRepository
    from core.application.services.context_registry import HierarchyLimitsRegistry


@dataclass
class ChildCreationResult:
    """Result of child agent creation."""

    agent: AgentSession
    created: bool  # False if limit was reached


class ChildAgentFactory:
    """Factory for creating child agents from ChildSpawned events.

    Single Responsibility: Create child agents with proper limits propagation.

    Provides:
    - Agent count tracking (source of truth for max_total_agents enforcement)
    - Hierarchy limits propagation to children
    - Manager config defaults for PENDING children

    Note: Limit enforcement is done by CheckLimitViolations pipeline step,
    which queries this factory for real-time agent counts.
    """

    def __init__(
        self,
        repository: "AgentRepository",
        limits_registry: "HierarchyLimitsRegistry",
        max_total_agents: int = -1,  # -1 means unlimited
        manager_config: "ManagerConfig | None" = None,
    ) -> None:
        self._repository = repository
        self._limits_registry = limits_registry
        self._max_total_agents = max_total_agents
        self._manager_config = manager_config
        self._total_created: int = 0

    def reset(self, initial_count: int = 0) -> None:
        """Reset factory state for a new run."""
        self._total_created = initial_count

    @property
    def total_created(self) -> int:
        """Get total number of agents created."""
        return self._total_created

    @property
    def max_total_agents(self) -> int:
        """Get the max total agents limit (-1 means unlimited)."""
        return self._max_total_agents

    def is_at_agent_limit(self) -> bool:
        """Check if we've reached the max_total_agents limit."""
        if self._max_total_agents < 0:
            return False
        return self._total_created >= self._max_total_agents

    def _apply_manager_config(self, config: dict[str, Any]) -> dict[str, Any]:
        """Apply manager config defaults to child config.

        Overrides LLM-generated model names with configured values to prevent
        invalid model names (e.g., "claude-3-5-sonnet" without date suffix).
        Handles both heuristic/hybrid (base) and per_operation strategies.
        """
        if self._manager_config is None:
            return config

        # Deep copy to avoid mutating original
        result = dict(config)
        manager_model = self._manager_config.model
        manager_temp = self._manager_config.temperature
        manager_max_tokens = self._manager_config.max_tokens

        # Handle heuristic/hybrid strategy (has "base" field)
        if "base" in result and isinstance(result["base"], dict):
            result["base"] = dict(result["base"])
            result["base"]["model"] = manager_model
            result["base"]["temperature"] = manager_temp
            result["base"]["max_tokens"] = manager_max_tokens

        # Handle per_operation strategy (has complexity_evaluation, task_decomposition)
        for op_key in ("complexity_evaluation", "task_decomposition"):
            if op_key in result and isinstance(result[op_key], dict):
                result[op_key] = dict(result[op_key])
                result[op_key]["model"] = manager_model
                result[op_key]["temperature"] = manager_temp
                result[op_key]["max_tokens"] = manager_max_tokens

        return result

    async def create_from_event(
        self,
        event: ChildSpawned,
        parent_id: UUID,
    ) -> ChildCreationResult:
        """Create a child agent from a ChildSpawned event.

        Limit checking is done by CheckLimitViolations pipeline step before
        events are emitted. Propagates hierarchy limits and spawn payload to child.
        Applies manager config defaults for PENDING children.
        """
        child_role = AgentRole(event.child_role)
        child_config = event.child_config

        # Apply manager config to override LLM-generated model names
        # This ensures the configured model always takes precedence over
        # potentially invalid model names generated by the LLM (e.g., "claude-3-5-sonnet"
        # without date suffix). Applied to all roles, not just PENDING.
        child_config = self._apply_manager_config(child_config)

        child = AgentSession.create(
            agent_id=event.child_id,
            role=child_role,
            config=child_config,
            parent_id=parent_id,
            sibling_index=event.sibling_index,
        )
        child.assign_task(event.subtask.description)

        # Propagate hierarchy limits
        self._limits_registry.propagate_to_child(parent_id, event.child_id)

        # Set spawn payload if available in event
        if event.parent_context:
            spawn_payload = SpawnPayload.model_validate(event.parent_context)
            child.set_spawn_payload(spawn_payload)

        # Persist the new agent
        await self._repository.save_new_agent(child)
        self._total_created += 1

        return ChildCreationResult(agent=child, created=True)

    async def create_children_from_events(
        self,
        events: list[ChildSpawned],
        parent_id: UUID,
    ) -> list[ChildCreationResult]:
        """Create multiple child agents from ChildSpawned events.

        Limit checking is done by CheckLimitViolations pipeline step before
        this method is called. This method assumes all events are valid.

        Returns:
            List of created children.
        """
        results: list[ChildCreationResult] = []
        for event in events:
            result = await self.create_from_event(event, parent_id)
            results.append(result)
        return results
